### ISSUE TITLE
Verify unique job i/o names

### ISSUE THREAD

**Issue by lorenzwalthert** [stiebels/sagemaker-rightline#58]
Hi, interesting package

I just got:

> ClientError: Failed to invoke sagemaker:CreateProcessingJob. Error Details: Input and Output names must be globally unique: [data]

when creating a pipeline in the last step in my pipeline since two inputs/outputs have the same name. -.-

Asserting this should also be possible and a meaningful usecase for your package? I was not sure if `StepInputsAsExpected` covered it already, since I am not familiar with the package. If needed, I can provide more context.

**Comment by stiebels** [comment]
Hi @lorenzwalthert 
Thanks for the suggestion!

Are you seeing this error when creating the Pipeline object, upserting, starting or during execution/when that specific job starts? It would help if you could provide a minimum code snippet to reproduce the error.

**Comment by stiebels** [comment]
I think this feature will help validate your case: https://github.com/stiebels/sagemaker-rightline/pull/65
Feel free to have a look and let me know! Thanks for the suggestion!

**Comment by lorenzwalthert** [comment]
Great, thanks. Hope I can find time to catch up with it.
