### ISSUE TITLE
Create .rst docs and publish them to gh pages

### ISSUE THREAD

**Issue by stiebels** [stiebels/sagemaker-rightline#8]

**Comment by dipanjank** [comment]
@stiebels, as repository owner, can you please follow these steps to import this project in ReadTheDocs? https://docs.readthedocs.io/en/stable/tutorial/index.html#importing-the-project-to-read-the-docs

**Comment by stiebels** [comment]
Thanks, done! https://readthedocs.org/projects/sagemaker-rightline/
